name: loyapy
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #  bloc & clean architecture
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  flutter_localizations:
    sdk: flutter
  intl:  0.19.0
  shared_preferences: ^2.5.3
  responsive_framework: ^1.5.1
  flutter_screenutil: ^5.9.3
  logger: ^2.5.0
  get_it: ^8.0.3
  carousel_slider: ^5.0.0
  flutter_html: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter:
  assets:
    - assets/lang/
    - assets/png/
    - assets/svg/
    - assets/category/
    - assets/product/
    - assets/social/

  uses-material-design: true



flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/png/logo_bg_white.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/png/logo_without_bg.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"


