// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx8d4ygcow8BzvXis8TCytPuxpzwXX2IM',
    appId: '1:737388060859:web:03f30f362d43d73749099e',
    messagingSenderId: '737388060859',
    projectId: 'loyapy-6078a',
    authDomain: 'loyapy-6078a.firebaseapp.com',
    storageBucket: 'loyapy-6078a.firebasestorage.app',
    measurementId: 'G-KSV0DC4NJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiZF_sFExXXhT-wFACr7QKGDV4RRQEETk',
    appId: '1:737388060859:android:c72cd710a64e8f8e49099e',
    messagingSenderId: '737388060859',
    projectId: 'loyapy-6078a',
    storageBucket: 'loyapy-6078a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe9fLwf9UWCE63ms2Q4EPHekWQH_AXupk',
    appId: '1:737388060859:ios:465246cf1182e3e549099e',
    messagingSenderId: '737388060859',
    projectId: 'loyapy-6078a',
    storageBucket: 'loyapy-6078a.firebasestorage.app',
    iosBundleId: 'com.loyapy.loyapy',
  );
}
